-- 清空 user_management 与 warehouse 的全部业务数据，保留数据库和表结构。
CREATE DATABASE IF NOT EXISTS user_management
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE user_management;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM ai_messages;
DELETE FROM ai_conversations;
DELETE FROM users;
ALTER TABLE ai_messages AUTO_INCREMENT = 1;
ALTER TABLE ai_conversations AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;

CREATE DATABASE IF NOT EXISTS warehouse
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE warehouse;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM income;
DELETE FROM expense;
DELETE FROM record;
DELETE FROM stock;
DELETE FROM category;
ALTER TABLE income AUTO_INCREMENT = 1;
ALTER TABLE expense AUTO_INCREMENT = 1;
ALTER TABLE record AUTO_INCREMENT = 1;
ALTER TABLE stock AUTO_INCREMENT = 1;
ALTER TABLE category AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;
